set(FILES
    Tests/JoltPhysicsTestEnvironment.cpp
    Tests/JoltPhysicsTestEnvironment.h
    Tests/JoltTestWarningCatcher.h
    Tests/JoltSystemTests.cpp
    Tests/JoltSettingsRegistryTests.cpp
    Tests/JoltSolverSettingsTests.cpp
    Tests/JoltInternalEdgeRemovalTests.cpp
    Tests/JoltSceneTests.cpp
    Tests/JoltComponentSerializationTests.cpp
    Tests/JoltScriptReflectionTests.cpp
    Tests/JoltHeightfieldTests.cpp
    Tests/JoltCollisionFilteringTests.cpp
    Tests/JoltSceneQueryTests.cpp
    Tests/JoltMaterialTests.cpp
    Tests/JoltMeshColliderTests.cpp
    Tests/JoltMeshAssetTests.cpp
    Tests/JoltTriggerTests.cpp
    Tests/JoltCollisionEventTests.cpp
    Tests/JoltRagdollTests.cpp
    Tests/JoltRigidBodyTests.cpp
    Tests/JoltComponentBodyCreationTests.cpp
    Tests/JoltCharacterTests.cpp
    Tests/JoltStateRecorderTests.cpp
    Tests/JoltJointTests.cpp
    Tests/JoltSoftBodyTests.cpp
    Tests/JoltVehicleTests.cpp
)
