set(FILES
    Source/Editor/JoltPhysicsEditorSystemComponent.cpp
    Source/Editor/JoltPhysicsEditorSystemComponent.h
    Source/Editor/EditorComponentDescriptors.cpp
    Source/Editor/EditorComponentDescriptors.h
    Source/Editor/JoltEditorSettingsRegistryManager.cpp
    Source/Editor/JoltEditorSettingsRegistryManager.h
    Source/Editor/Components/EditorJoltColliderComponentBase.cpp
    Source/Editor/Components/EditorJoltColliderComponentBase.h
    Source/Editor/Components/EditorJoltBoxColliderComponent.cpp
    Source/Editor/Components/EditorJoltBoxColliderComponent.h
)
