set(FILES
    Source/Clients/JoltPhysicsSystemComponent.cpp
    Source/Clients/JoltPhysicsSystemComponent.h
    Source/Clients/ComponentDescriptors.cpp
    Source/Clients/ComponentDescriptors.h
    Source/Clients/DefaultWorldComponent.cpp
    Source/Clients/DefaultWorldComponent.h
    Source/Clients/Components/JoltColliderComponentBase.cpp
    Source/Clients/Components/JoltColliderComponentBase.h
    Source/Clients/Components/JoltBoxColliderComponent.cpp
    Source/Clients/Components/JoltBoxColliderComponent.h
    Source/Clients/Components/JoltSphereColliderComponent.cpp
    Source/Clients/Components/JoltSphereColliderComponent.h
    Source/Clients/Components/JoltCapsuleColliderComponent.cpp
    Source/Clients/Components/JoltCapsuleColliderComponent.h
    Source/Clients/Components/JoltRigidBodyComponent.cpp
    Source/Clients/Components/JoltRigidBodyComponent.h
    Source/Clients/Components/JoltStaticRigidBodyComponent.cpp
    Source/Clients/Components/JoltStaticRigidBodyComponent.h
    Source/Clients/Components/JoltStaticCompoundColliderComponent.cpp
    Source/Clients/Components/JoltStaticCompoundColliderComponent.h
    Source/Clients/Components/JoltHeightfieldColliderComponent.cpp
    Source/Clients/Components/JoltHeightfieldColliderComponent.h
    Source/Clients/Components/JoltCharacterControllerComponent.cpp
    Source/Clients/Components/JoltCharacterControllerComponent.h
    Source/Character/JoltCharacter.cpp
    Source/Character/JoltCharacter.h
    Source/Debug/JoltDebugRenderer.cpp
    Source/Debug/JoltDebugRenderer.h
    Source/Configuration/JoltSettingsRegistryManager.cpp
    Source/Configuration/JoltSettingsRegistryManager.h
    Source/System/JoltSystem.cpp
    Source/System/JoltSystem.h
    Source/System/JoltAllocator.cpp
    Source/System/JoltAllocator.h
    Source/System/CollisionLayerFilters.cpp
    Source/System/CollisionLayerFilters.h
    Source/Scene/JoltScene.cpp
    Source/Scene/JoltScene.h
    Source/Scene/JoltSceneInterface.cpp
    Source/Scene/JoltSceneInterface.h
    Source/Scene/JoltSceneQueryHelpers.cpp
    Source/Scene/JoltSceneQueryHelpers.h
    Source/Material/JoltMaterial.cpp
    Source/Material/JoltMaterial.h
    Source/Material/JoltMaterialManager.cpp
    Source/Material/JoltMaterialManager.h
    Source/RigidBody/JoltRigidBody.cpp
    Source/RigidBody/JoltRigidBody.h
    Source/RigidBody/JoltStaticRigidBody.cpp
    Source/RigidBody/JoltStaticRigidBody.h
    Source/Shape/JoltHeightfieldUtils.cpp
    Source/Shape/JoltHeightfieldUtils.h
    Source/Shape/JoltShapeUtils.cpp
    Source/Shape/JoltShapeUtils.h
    Source/Utils/Conversions.cpp
    Source/Utils/Conversions.h
    Source/Utils/ReflectionUtils.h
)
