set(FILES
    Include/JoltPhysics/JoltModuleGlobals.h
    Include/JoltPhysics/JoltPhysicsBus.h
    Include/JoltPhysics/JoltVehicleConfiguration.h
    Include/JoltPhysics/JoltCharacterGameplayBus.h
    Include/JoltPhysics/Configuration/JoltConfiguration.h
    Include/JoltPhysics/JoltSoftBodyBus.h
    Include/JoltPhysics/Pipeline/JoltMeshAsset.h
)
