set(FILES
    Source/Clients/JoltPhysicsSystemComponent.cpp
    Source/Clients/JoltPhysicsSystemComponent.h
    Source/Clients/ComponentDescriptors.cpp
    Source/Clients/ComponentDescriptors.h
    Source/Clients/DefaultWorldComponent.cpp
    Source/Clients/DefaultWorldComponent.h
    Source/Clients/Components/JoltColliderComponentBase.cpp
    Source/Clients/Components/JoltColliderComponentBase.h
    Source/Clients/Components/JoltBoxColliderComponent.cpp
    Source/Clients/Components/JoltBoxColliderComponent.h
    Source/Clients/Components/JoltSphereColliderComponent.cpp
    Source/Clients/Components/JoltSphereColliderComponent.h
    Source/Clients/Components/JoltCapsuleColliderComponent.cpp
    Source/Clients/Components/JoltCapsuleColliderComponent.h
    Source/Clients/Components/JoltCylinderColliderComponent.cpp
    Source/Clients/Components/JoltCylinderColliderComponent.h
    Source/Clients/Components/JoltMeshColliderComponent.cpp
    Source/Clients/Components/JoltMeshColliderComponent.h
    Source/Clients/Components/JoltRigidBodyComponent.cpp
    Source/Clients/Components/JoltRigidBodyComponent.h
    Source/Clients/Components/JoltStaticRigidBodyComponent.cpp
    Source/Clients/Components/JoltStaticRigidBodyComponent.h
    Source/Clients/Components/JoltStaticCompoundColliderComponent.cpp
    Source/Clients/Components/JoltStaticCompoundColliderComponent.h
    Source/Clients/Components/JoltHeightfieldColliderComponent.cpp
    Source/Clients/Components/JoltHeightfieldColliderComponent.h
    Source/Clients/Components/JoltCharacterControllerComponent.cpp
    Source/Clients/Components/JoltCharacterControllerComponent.h
    Source/Clients/Components/JoltJointComponentBase.cpp
    Source/Clients/Components/JoltJointComponentBase.h
    Source/Clients/Components/JoltJointComponents.cpp
    Source/Clients/Components/JoltJointComponents.h
    Source/Clients/Components/JoltVehicleComponent.cpp
    Source/Clients/Components/JoltVehicleComponent.h
    Source/Character/JoltCharacter.cpp
    Source/Character/JoltCharacter.h
    Source/Character/JoltRagdoll.cpp
    Source/Character/JoltRagdoll.h
    Source/Character/JoltRagdollNode.cpp
    Source/Character/JoltRagdollNode.h
    Source/Character/JoltSkeletonMapper.cpp
    Source/Character/JoltSkeletonMapper.h
    Source/Clients/Components/JoltSoftBodyComponent.cpp
    Source/Clients/Components/JoltSoftBodyComponent.h
    Source/Joint/JoltJoint.cpp
    Source/Joint/JoltJoint.h
    Source/Joint/JoltJointConfiguration.cpp
    Source/Joint/JoltJointConfiguration.h
    Source/Vehicle/JoltVehicle.cpp
    Source/Vehicle/JoltVehicle.h
    Source/Vehicle/JoltVehicleConfiguration.cpp
    Source/Vehicle/JoltVehicleConfiguration.h
    Source/Debug/JoltDebugRenderer.cpp
    Source/Debug/JoltDebugRenderer.h
    Source/Configuration/JoltSettingsRegistryManager.cpp
    Source/Configuration/JoltSettingsRegistryManager.h
    Source/System/JoltSystem.cpp
    Source/System/JoltSystem.h
    Source/System/JoltAllocator.cpp
    Source/System/JoltAllocator.h
    Source/System/CollisionLayerFilters.cpp
    Source/System/CollisionLayerFilters.h
    Source/Scene/JoltScene.cpp
    Source/Scene/JoltScene.h
    Source/Scene/JoltSceneInterface.cpp
    Source/Scene/JoltSceneInterface.h
    Source/Scene/JoltSceneQueryHelpers.cpp
    Source/Scene/JoltSceneQueryHelpers.h
    Source/Material/JoltMaterial.cpp
    Source/Material/JoltMaterial.h
    Source/Material/JoltMaterialManager.cpp
    Source/Material/JoltMaterialManager.h
    Source/RigidBody/JoltRigidBody.cpp
    Source/RigidBody/JoltRigidBody.h
    Source/RigidBody/JoltStaticRigidBody.cpp
    Source/RigidBody/JoltStaticRigidBody.h
    Source/Shape/JoltCylinderShapeConfiguration.cpp
    Source/Shape/JoltCylinderShapeConfiguration.h
    Source/Shape/JoltHeightfieldUtils.cpp
    Source/Shape/JoltHeightfieldUtils.h
    Source/Shape/JoltMeshUtils.cpp
    Source/Shape/JoltMeshUtils.h
    Source/Shape/JoltShape.cpp
    Source/Shape/JoltShape.h
    Source/Shape/JoltShapeUtils.cpp
    Source/Shape/JoltShapeUtils.h
    Source/SoftBody/JoltSoftBody.cpp
    Source/SoftBody/JoltSoftBody.h
    Source/SoftBody/JoltSoftBodyRender.cpp
    Source/SoftBody/JoltSoftBodyRender.h
    Source/Utils/Conversions.cpp
    Source/Utils/Conversions.h
    Source/Utils/ReflectionUtils.h
    Source/Utils/JoltComponentUtils.cpp
    Source/Utils/JoltComponentUtils.h
)
