set(FILES
    Source/Editor/JoltPhysicsEditorSystemComponent.cpp
    Source/Editor/JoltPhysicsEditorSystemComponent.h
    Source/Editor/EditorComponentDescriptors.cpp
    Source/Editor/EditorComponentDescriptors.h
    Source/Editor/JoltEditorSettingsRegistryManager.cpp
    Source/Editor/JoltEditorSettingsRegistryManager.h
    Source/Editor/Components/EditorJoltColliderComponentBase.cpp
    Source/Editor/Components/EditorJoltColliderComponentBase.h
    Source/Editor/Components/EditorJoltColliderDrawUtils.h
    Source/Editor/Components/EditorJoltBoxColliderComponent.cpp
    Source/Editor/Components/EditorJoltBoxColliderComponent.h
    Source/Editor/Components/EditorJoltSphereColliderComponent.cpp
    Source/Editor/Components/EditorJoltSphereColliderComponent.h
    Source/Editor/Components/EditorJoltCapsuleColliderComponent.cpp
    Source/Editor/Components/EditorJoltCapsuleColliderComponent.h
    Source/Editor/Components/EditorJoltRigidBodyComponent.cpp
    Source/Editor/Components/EditorJoltRigidBodyComponent.h
    Source/Editor/Components/EditorJoltStaticRigidBodyComponent.cpp
    Source/Editor/Components/EditorJoltStaticRigidBodyComponent.h
    Source/Editor/Components/EditorJoltHeightfieldColliderComponent.cpp
    Source/Editor/Components/EditorJoltHeightfieldColliderComponent.h
    Source/Editor/Components/EditorJoltStaticCompoundColliderComponent.cpp
    Source/Editor/Components/EditorJoltStaticCompoundColliderComponent.h
    Source/Editor/Components/EditorJoltMutableCompoundColliderComponent.cpp
    Source/Editor/Components/EditorJoltMutableCompoundColliderComponent.h
    Source/Editor/Components/EditorJoltCharacterControllerComponent.cpp
    Source/Editor/Components/EditorJoltCharacterControllerComponent.h
    Source/Editor/Components/EditorJoltVehicleComponent.cpp
    Source/Editor/Components/EditorJoltVehicleComponent.h
)
