set(FILES
    Tests/JoltPhysicsEditorTestEnvironment.cpp
    Tests/JoltPhysicsEditorTestEnvironment.h
    Tests/JoltPhysicsEditorSystemComponentTests.cpp
    Tests/JoltEditorWorldColliderTests.cpp
    Tests/JoltEditorDebugDrawTests.cpp
    Tests/JoltCharacterControllerComponentModeTests.cpp
    Tests/JoltEditorColliderSerializationTests.cpp
    Tests/JoltEditorColliderGeometryTests.cpp
    Tests/JoltEditorConvexDecompositionTests.cpp
    Tests/JoltEditorPrimitiveFitTests.cpp
    Tests/JoltColliderOffsetComponentModeTests.cpp
    Tests/JoltJointComponentModeTests.cpp
    Tests/JoltEditorJointHelpersTests.cpp
    Tests/JoltVehicleComponentModeTests.cpp
    Tests/JoltEditorVehicleSettleTests.cpp
    Tests/JoltEditorHeightfieldDrawTests.cpp
    Tests/JoltEditorSoftBodyPreviewTests.cpp
)
