set(FILES
    Source/Editor/JoltPhysicsEditorSystemComponent.cpp
    Source/Editor/JoltPhysicsEditorSystemComponent.h
    Source/Editor/EditorComponentDescriptors.cpp
    Source/Editor/EditorComponentDescriptors.h
    Source/Editor/JoltEditorSettingsRegistryManager.cpp
    Source/Editor/JoltEditorSettingsRegistryManager.h
    Source/Editor/PropertyHandlers/CollisionPropertyUtils.h
    Source/Editor/PropertyHandlers/PropertyTypes.cpp
    Source/Editor/PropertyHandlers/PropertyTypes.h
    Source/Editor/PropertyHandlers/CollisionLayerWidget.cpp
    Source/Editor/PropertyHandlers/CollisionLayerWidget.h
    Source/Editor/PropertyHandlers/CollisionGroupWidget.cpp
    Source/Editor/PropertyHandlers/CollisionGroupWidget.h
    Source/Editor/Components/EditorJoltColliderComponentBase.cpp
    Source/Editor/Components/EditorJoltColliderComponentBase.h
    Source/Editor/Components/EditorJoltColliderDrawUtils.h
    Source/Editor/Components/EditorJoltBoxColliderComponent.cpp
    Source/Editor/Components/EditorJoltBoxColliderComponent.h
    Source/Editor/Components/EditorJoltSphereColliderComponent.cpp
    Source/Editor/Components/EditorJoltSphereColliderComponent.h
    Source/Editor/Components/EditorJoltCapsuleColliderComponent.cpp
    Source/Editor/Components/EditorJoltCapsuleColliderComponent.h
    Source/Editor/Components/EditorJoltCylinderColliderComponent.cpp
    Source/Editor/Components/EditorJoltCylinderColliderComponent.h
    Source/Editor/Components/EditorJoltMeshColliderComponent.cpp
    Source/Editor/Components/EditorJoltMeshColliderComponent.h
    Source/Editor/Components/EditorJoltRigidBodyComponent.cpp
    Source/Editor/Components/EditorJoltRigidBodyComponent.h
    Source/Editor/Components/EditorJoltStaticRigidBodyComponent.cpp
    Source/Editor/Components/EditorJoltStaticRigidBodyComponent.h
    Source/Editor/Components/EditorJoltHeightfieldColliderComponent.cpp
    Source/Editor/Components/EditorJoltHeightfieldColliderComponent.h
    Source/Editor/Components/EditorJoltStaticCompoundColliderComponent.cpp
    Source/Editor/Components/EditorJoltStaticCompoundColliderComponent.h
    Source/Editor/Components/EditorJoltMutableCompoundColliderComponent.cpp
    Source/Editor/Components/EditorJoltMutableCompoundColliderComponent.h
    Source/Editor/Components/EditorJoltCharacterControllerComponent.cpp
    Source/Editor/Components/EditorJoltCharacterControllerComponent.h
    Source/Editor/Components/EditorJoltVehicleComponent.cpp
    Source/Editor/Components/EditorJoltVehicleComponent.h
    Source/Editor/Components/EditorJoltJointComponentBase.cpp
    Source/Editor/Components/EditorJoltJointComponentBase.h
    Source/Editor/Components/EditorJoltFixedJointComponent.cpp
    Source/Editor/Components/EditorJoltFixedJointComponent.h
    Source/Editor/Components/EditorJoltBallJointComponent.cpp
    Source/Editor/Components/EditorJoltBallJointComponent.h
    Source/Editor/Components/EditorJoltHingeJointComponent.cpp
    Source/Editor/Components/EditorJoltHingeJointComponent.h
    Source/Editor/Components/EditorJoltPrismaticJointComponent.cpp
    Source/Editor/Components/EditorJoltPrismaticJointComponent.h
    Source/Editor/Components/EditorJoltD6JointComponent.cpp
    Source/Editor/Components/EditorJoltD6JointComponent.h
    Source/Editor/Components/EditorJoltDistanceJointComponent.cpp
    Source/Editor/Components/EditorJoltDistanceJointComponent.h
    Source/Editor/Components/EditorJoltConeJointComponent.cpp
    Source/Editor/Components/EditorJoltConeJointComponent.h
    Source/Editor/Components/EditorJoltSwingTwistJointComponent.cpp
    Source/Editor/Components/EditorJoltSwingTwistJointComponent.h
)
