set(FILES
    Tests/JoltPhysicsEditorTestEnvironment.cpp
    Tests/JoltPhysicsEditorTestEnvironment.h
    Tests/JoltPhysicsEditorSystemComponentTests.cpp
    Tests/JoltEditorDebugDrawTests.cpp
    Tests/JoltCharacterControllerComponentModeTests.cpp
    Tests/JoltEditorColliderSerializationTests.cpp
    Tests/JoltEditorColliderGeometryTests.cpp
)
