set(FILES
    Tests/JoltPhysicsTestEnvironment.cpp
    Tests/JoltPhysicsTestEnvironment.h
    Tests/JoltSystemTests.cpp
    Tests/JoltSceneTests.cpp
    Tests/JoltComponentSerializationTests.cpp
    Tests/JoltHeightfieldTests.cpp
    Tests/JoltCollisionFilteringTests.cpp
    Tests/JoltSceneQueryTests.cpp
    Tests/JoltMaterialTests.cpp
    Tests/JoltTriggerTests.cpp
    Tests/JoltCollisionEventTests.cpp
    Tests/JoltRigidBodyTests.cpp
    Tests/JoltComponentBodyCreationTests.cpp
    Tests/JoltCharacterTests.cpp
    Tests/JoltJointTests.cpp
    Tests/JoltVehicleTests.cpp
)
