set(FILES
    Tests/JoltPhysicsTestEnvironment.cpp
    Tests/JoltPhysicsTestEnvironment.h
    Tests/JoltSystemTests.cpp
    Tests/JoltSceneTests.cpp
    Tests/JoltComponentSerializationTests.cpp
    Tests/JoltCollisionFilteringTests.cpp
    Tests/JoltSceneQueryTests.cpp
    Tests/JoltMaterialTests.cpp
    Tests/JoltTriggerTests.cpp
    Tests/JoltRigidBodyTests.cpp
    Tests/JoltComponentBodyCreationTests.cpp
)
