set(FILES
    Tests/JoltPhysicsEditorTestEnvironment.cpp
    Tests/JoltPhysicsEditorTestEnvironment.h
    Tests/JoltPhysicsEditorSystemComponentTests.cpp
    Tests/JoltEditorDebugDrawTests.cpp
    Tests/JoltCharacterControllerComponentModeTests.cpp
    Tests/JoltEditorColliderSerializationTests.cpp
    Tests/JoltEditorColliderGeometryTests.cpp
    Tests/JoltEditorConvexDecompositionTests.cpp
    Tests/JoltEditorPrimitiveFitTests.cpp
    Tests/JoltJointComponentModeTests.cpp
    Tests/JoltVehicleComponentModeTests.cpp
    Tests/JoltEditorHeightfieldDrawTests.cpp
)
